"""add_similar_books_and_popularity_tables

Revision ID: a4e20bb1deb6
Revises: a5f7f7c1f231
Create Date: 2026-02-25 11:58:39.911862

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4e20bb1deb6"
down_revision: str | Sequence[str] | None = "a5f7f7c1f231"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_popularity",
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("book_ids", sa.JSON(), nullable=False),
        sa.Column("recs_version", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("scope"),
    )
    op.create_table(
        "book_similarities",
        sa.Column("book_id", sa.String(length=36), nullable=False),
        sa.Column("neighbor_ids", sa.JSON(), nullable=False),
        sa.Column("recs_version", sa.Text(), nullable=True),
        sa.Column("algo_id", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("book_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_similarities")
    op.drop_table("book_popularity")
    # ### end Alembic commands ###
